In [21]:
##Section A: Data Structures & Control Structures

numbers = [10, 20, 30, 40, 50] #list

# append
numbers.append(60)
print(numbers)

# extend
numbers.extend([70, 80])
print(numbers)

# insert
numbers.insert(2, 25)
print(numbers)

# remove
numbers.remove(40)
print(numbers)

# pop
numbers.pop()
print(numbers)

# index
x = numbers.index(30)
print("Index of 30 is", x)

# count
y = numbers.count(20)
print("Count of 20 is", y)

# sort
numbers.sort()
print(numbers)

# reverse
numbers.reverse()
print(numbers)

# clear
numbers.clear()
print(numbers)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 25, 30, 40, 50, 60, 70, 80]
[10, 20, 25, 30, 50, 60, 70, 80]
[10, 20, 25, 30, 50, 60, 70]
Index of 30 is 3
Count of 20 is 1
[10, 20, 25, 30, 50, 60, 70]
[70, 60, 50, 30, 25, 20, 10]
[]


In [16]:
students = ("Ravi", "Sita", "Rahul")
print(students)
# students[1] = "Priya"
# This gives an error because tuples are immutable.
# Immutable means values cannot be changed after creation.

('Ravi', 'Sita', 'Rahul')


In [17]:
numbers = {1, 2, 3, 4, 2, 3, 5, 1}
print(numbers)

# Sets automatically remove duplicate values.
# Therefore only unique values are displayed.

{1, 2, 3, 4, 5}


In [18]:
#dictionary
person = {
    "name": "Naveen",
    "age": 23,
    "city": "Chittoor"
}
# Updating age
person["age"] = 24

# Adding email
person["email"] = "naveen@gmail.com"
print(person)

{'name': 'Naveen', 'age': 24, 'city': 'Chittoor', 'email': 'naveen@gmail.com'}


In [19]:
# Age of the person
age = 20

# Check if age is 18 or above
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [20]:
# Finding grade based on marks

marks = 82

if marks >= 90:
    print("Grade A")

elif marks >= 75:
    print("Grade B")

elif marks >= 50:
    print("Grade C")

else:
    print("Fail")

Grade B


Section B: Numpy

In [24]:
import numpy as np

# Creating a scalar value
a = np.array(5)
print(a)

# Creating a 1D array
b = np.array([1, 2, 3, 4, 5])
print(b)

# Creating a 2D array
c = np.array([[10, 20, 30],
              [40, 50, 60]])

print(c)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [25]:
import numpy as np

# Generating random integers between 0 and 100 and in 4X4 matrix
arr = np.random.randint(0, 101, (4, 4))

print(arr)

[[76 82 93 97]
 [93 47 74 48]
 [ 3 49 85 86]
 [69 58 60 54]]


In [27]:
import numpy as np
import pandas as pd

# Creating a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Converting array into dataframe with a columns A,B,C
df = pd.DataFrame(arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas

In [ ]:
import pandas as pd
import numpy as np

# Student details data

data = {
    "Name": ["Ravi", "Sita", "Rahul", "Priya", "Kiran",
             "Asha", "Vijay", "Meena", "Arun", "Ravi"],

    "Age": [22, 24, 21, 25, 23,
            26, 27, 22, 24, 22],

    "City": ["Hyderabad", "Chennai", "Bangalore", "Mumbai", "Delhi",
             "Pune", "Hyderabad", "Chennai", "Delhi", "Hyderabad"],

    "Salary": [25000, 30000, np.nan, 35000, 28000,
               40000, 45000, 30000, 28000, 25000]
}

df = pd.DataFrame(data)

# Checking dataframe information
df.info()

# statistics
print(df.describe())

# Displaying only Name and City columns
print(df[["Name", "City"]])

# Removing City column
df = df.drop("City", axis=1)

# Replacing missing salary value with average salary(mean)
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# Removing duplicate records
df = df.drop_duplicates()

# Final dataframe
print(df)