In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv("adult_with_headers.csv")

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K


In [43]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64 
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64 
 11  capital_loss    32561 non-null  int64 
 12  hours_per_week  32561 non-null  int64 
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [44]:

print(df.describe())

                age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000  


In [45]:

print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64


In [46]:
# Numerical columns

num_cols = df.select_dtypes(include=["int64","float64"])

print(num_cols.columns)

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')


In [47]:
# Standard Scaling

from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

standard_scaled = standard_scaler.fit_transform(num_cols)

print(standard_scaled[:5])

[[ 0.03067056 -1.06361075  1.13473876  0.1484529  -0.21665953 -0.03542945]
 [ 0.83710898 -1.008707    1.13473876 -0.14592048 -0.21665953 -2.22215312]
 [-0.04264203  0.2450785  -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 [ 1.05704673  0.42580136 -1.19745882 -0.14592048 -0.21665953 -0.03542945]
 [-0.77576787  1.40817572  1.13473876 -0.14592048 -0.21665953 -0.03542945]]


Standard Scaling is useful when data contains different scales and when algorithms assume normally distributed data.

In [48]:
# Min Max Scaling

from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

minmax_scaled = minmax_scaler.fit_transform(num_cols)

print(minmax_scaled[:5])

[[0.30136986 0.0443019  0.8        0.02174022 0.         0.39795918]
 [0.45205479 0.0482376  0.8        0.         0.         0.12244898]
 [0.28767123 0.13811345 0.53333333 0.         0.         0.39795918]
 [0.49315068 0.15106831 0.4        0.         0.         0.39795918]
 [0.15068493 0.22148843 0.8        0.         0.         0.39795918]]


Min-Max Scaling is useful when features need to be transformed into a fixed range between 0 and 1.

In [49]:
#2. Encoding techniques
# One Hot Encoding

onehot_cols = ["sex","race","income"]

onehot_df = pd.get_dummies(df,
                           columns=onehot_cols)

print(onehot_df.head())

   age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship  capital_gain  \
0        Never-married        Adm-clerical   Not-in-family          2174   
1   Married-civ-spouse     Exec-managerial         Husband             0   
2             Divorced   Handlers-cleaners   Not-in-family             0   
3   Married-civ-spouse   Handlers-cleaners         Husband             0   
4   Married-civ-spouse      Prof-specialty            Wife             0   

   capital_loss  ...  native_country sex_ Female  sex_ Male  \
0             0  ...   United-States       False       True   
1             0  ...   United-St

In [50]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder

label_cols = [
    "workclass",
    "education",
    "marital_status",
    "occupation",
    "relationship",
    "native_country"
]

le = LabelEncoder()

for col in label_cols:

    df[col] = le.fit_transform(df[col])

print(df.head())

   age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   occupation  relationship    race      sex  capital_gain  capital_loss  \
0           1             1   White     Male          2174             0   
1           4             0   White     Male             0             0   
2           6             1   White     Male             0             0   
3           6             0   Black     Male             0             0   
4          10             5   Black   Female             0             0   

   hours_per_week  native_country  income  
0              40              39   <=50K  
1              13           

One-Hot Encoding

Pros:
Does not create an order among categories.

Works well for nominal categorical data.



Cons:
Increases the number of columns.

Label Encoding

Pros:
Simple and easy to implement.
Uses less memory.

Cons:
May introduce an artificial order among categories.


In [51]:
# Creating new feature

df["age_hours"] = df["age"] * df["hours_per_week"]

print(df[["age", "hours_per_week", "age_hours"]].head())

   age  hours_per_week  age_hours
0   39              40       1560
1   50              13        650
2   38              40       1520
3   53              40       2120
4   28              40       1120


In [52]:
# Creating another feature

df["capital_total"] = df["capital_gain"] + df["capital_loss"]

print(df[["capital_gain",
          "capital_loss",
          "capital_total"]].head())

   capital_gain  capital_loss  capital_total
0          2174             0           2174
1             0             0              0
2             0             0              0
3             0             0              0
4             0             0              0


Feature 1: age_hours

This feature combines age and hours worked per week.
It may help capture the relationship between age and work effort.

Feature 2: capital_total

This feature combines capital gain and capital loss.
It provides overall capital-related information in a single feature.

In [54]:
# Applying log transformation

df["log_fnlwgt"] = np.log1p(df["fnlwgt"])

print(df[["fnlwgt", "log_fnlwgt"]].head())

   fnlwgt  log_fnlwgt
0   77516   11.258253
1   83311   11.330348
2  215646   12.281398
3  234721   12.366157
4  338409   12.732013


Log transformation was applied to the fnlwgt feature.

The fnlwgt column is positively skewed.
Applying log transformation helps reduce skewness and makes the distribution more balanced.